/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElElMessage: typeof import('element-plus/es')['ElElMessage']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElModal: typeof import('element-plus/es').ElModal
}
